Quartz component has minor issues with old versions of Quartz    HelloI have run into two issues using camel-quartz with old versions of Quartz (Quartz 1.6 and 1.7):1. With Quartz 1.6  at shutdown  I get a message:2010-11-12 02:41:22 965 DefaultShutdownStrategy.shutdownNow Error occurred while shutting down route: Consumer[quartz://importAnnuaireAgentsTimer?cron=0+30+2+*+*+%3F]. This exception will be ignored.java.lang.NoSuchMethodError: org.quartz.SchedulerMetaData.isJobStoreClustered()Z at org.apache.camel.component.quartz.QuartzComponent.isClustered(QuartzComponent.java:278) at org.apache.camel.component.quartz.QuartzComponent.removeJob(QuartzComponent.java:238) at org.apache.camel.component.quartz.QuartzEndpoint.removeTrigger(QuartzEndpoint.java:84) at org.apache.camel.component.quartz.QuartzEndpoint.consumerStopped(QuartzEndpoint.java:221) at org.apache.camel.component.quartz.QuartzConsumer.doStop(QuartzConsumer.java:44) at org.apache.camel.impl.ServiceSupport.stop(ServiceSupport.java:98) at org.apache.camel.impl.ServiceSupport.stop(ServiceSupport.java:122) at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:99) at org.apache.camel.impl.DefaultShutdownStrategy.shutdownNow(DefaultShutdownStrategy.java:235) at org.apache.camel.impl.DefaultShutdownStrategy$ShutdownTask.run(DefaultShutdownStrategy.java:386) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) at java.util.concurrent.FutureTask.run(FutureTask.java:138) at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) at java.lang.Thread.run(Thread.java:619)2. Starting of a delayed timer fails. I think warning the user would be a better idea.Patch is attached (it basically catches the NoSuchMethodError exceptions and acts accordingly)   