ImportExportTest doesn't detect lack of expected errors    I observed that ImportExportTest contains many test cases which do try/catch/assertSQLException  but none of them call fail() at the end of the try block. Example: public void testEarlyEndOfFile() throws Exception { Connection c = getConnection(); try { doImportFromFile(c  'extin/EndOfFile.txt'   'T4'   null   null   null  0); } catch (SQLException e) { assertSQLState('XIE0E'  e); } }I think this means that if the expected exception isn't thrown the test still passes.   