Unidiomatic error handling in TimestampArithTest    TimestampArithTest contains some error handling code that prevents the underlying error from being reported to the JUnit framework  and it may even terminate the JVM running the tests on some errors. Examples:This code prints the stack trace of the underlying error to the terminal  but it won't be included in the report from the JUnit framework: printStackTrace(sqle); fail('Unexpected exception from statement '' + sql + ''');This code terminates the JVM on error  preventing subsequent tests from running  and also preventing the JUnit framework to report the results from the tests that did run: } catch (Exception e) { System.out.println(s + ' is not a proper timestamp string.'); System.out.println(e.getClass().getName() + ': ' + e.getMessage()); e.printStackTrace(); System.exit(1); return null; }   