Problems running SecureServerTest and replication tests on Open JDK 7 for Mac OS X    I see the following errors when I run the JUnit tests on Open JDK 7 for Mac OS X:sanity is sane..START-SPAWNED:sysinfo STANDARD OUTPUT: exit code=1Tue Oct 11 10:15:02 PDT 2011 : Error getting SysInfo information.END-SPAWNED :sysinfo STANDARD OUTPUT:FSTART-SPAWNED:SpawnedNetworkServer STANDARD OUTPUT: exit code=143Tue Oct 11 10:14:54 PDT 2011 : Security manager installed using the Basic server security policy.Tue Oct 11 10:15:01 PDT 2011 : Warning: UnknkownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not known.Tue Oct 11 10:15:01 PDT 2011 : Apache Derby Network Server - 10.8.2.2 - (1181258) started and ready to accept connections on port 1527Tue Oct 11 10:15:02 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands Tue Oct 11 10:15:02 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands END-SPAWNED :SpawnedNetworkServer STANDARD OUTPUT:E.START-SPAWNED:sysinfo STANDARD OUTPUT: exit code=1Tue Oct 11 10:15:50 PDT 2011 : Error getting SysInfo information.END-SPAWNED :sysinfo STANDARD OUTPUT:FSTART-SPAWNED:SpawnedNetworkServer STANDARD OUTPUT: exit code=143Tue Oct 11 10:15:43 PDT 2011 : Security manager installed using the Basic server security policy.Tue Oct 11 10:15:50 PDT 2011 : Warning: UnknkownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not known.Tue Oct 11 10:15:50 PDT 2011 : Apache Derby Network Server - 10.8.2.2 - (1181258) started and ready to accept connections on port 1527Tue Oct 11 10:15:50 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands Tue Oct 11 10:15:50 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands END-SPAWNED :SpawnedNetworkServer STANDARD.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F.....START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F......................START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided  or not knownEND-SPAWNED :SpawnedNetworkServer ERROR OUTPUT:F.E.E.E.F.E.E.E.E.E.E.E.E.E.E.E.E.E.E.ETime: 5 033.075There were 20 errors:1) SecureServerTest( Opened = false  Authenticated= true  CustomDerbyProperties= null  WildCardHost= 0.0.0.0 )java.lang.Exception: DRDA_NeedLocalHost.S:host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands  at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.readResult(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.shutdown(Unknown Source) at org.apache.derby.drda.NetworkServerControl.shutdown(Unknown Source) at org.apache.derbyTesting.junit.NetworkServerTestSetup.tearDown(NetworkServerTestSetup.java:379) at junit.extensions.TestSetup$1.protect(TestSetup.java:22) at junit.extensions.TestSetup.run(TestSetup.java:25) at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)2) SecureServerTest( Opened = false  Authenticated= true  CustomDerbyProperties= null  WildCardHost= 0.00.000.0 )java.lang.Exception: DRDA_NeedLocalHost.S:host: localhost is not local to the server running on 0.0.0.0  so cannot be used for NetworkServerControl commands  at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.readResult(Unknown Source) at org.apache.derby.impl.drda.NetworkServerControlImpl.shutdown(Unknown Source) at org.apache.derby.drda.NetworkServerControl.shutdown(Unknown Source) at org.apache.derbyTesting.junit.NetworkServerTestSetup.tearDown(NetworkServerTestSetup.java:379) at junit.extensions.TestSetup$1.protect(TestSetup.java:22) at junit.extensions.TestSetup.run(TestSetup.java:25) at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)3) testReplication_Local_LogFilesSynched(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local.testReplication_Local_LogFilesSynched(ReplicationRun_Local.java:195) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 32 more4) testReplication_Local_1_InsertUpdateDeleteOnMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1.testReplication_Local_1_InsertUpdateDeleteOnMaster(ReplicationRun_Local_1.java:77) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 32 more5) testReplication_Local_1_Indexing(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1Indexing)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.makeReadyForReplication(ReplicationRun.java:2518) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1Indexing.testReplication_Local_1_Indexing(ReplicationRun_Local_1Indexing.java:70) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 33 more6) testReplication_Local_StateTest_part1_1(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_1.testReplication_Local_StateTest_part1_1(ReplicationRun_Local_StateTest_part1_1.java:96) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 32 more7) testReplication_Local_StateTest_part1_2(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_2.testReplication_Local_StateTest_part1_2(ReplicationRun_Local_StateTest_part1_2.java:104) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 32 more8) testReplication_Local_StateTest_part1_3(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_3)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_3.testReplication_Local_StateTest_part1_3(ReplicationRun_Local_StateTest_part1_3.java:95) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24) at junit.extensions.TestSetup$1.protect(TestSetup.java:21) at junit.extensions.TestSetup.run(TestSetup.java:25)Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source) at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source) at org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source) at org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source) at org.apache.derby.client.am.Statement.readPrepare(Unknown Source) at org.apache.derby.client.am.Statement.flowExecute(Unknown Source) at org.apache.derby.client.am.Statement.executeX(Unknown Source) ... 32 more9) testReplication_Local_StateTest_part2(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1  SQLSTATE: XSAI2  SQLERRMC: 384XSAI2.S at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868) at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part2.testReplication_Local_StateTest_part2(ReplicationRun_Local_StateTest_part2.java:97) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113) at org.apache.derbyTesting.functi