LDAP user authentication fails under a security manager    Running the test jdbcapi/secureUsers1.sql with a security manager results in:&gt; ERROR 08004: Connection refused : javax.naming.CommunicationException: noSuchMachine:389 &#91;Root exception is java.security.AccessControlException: access denied (java.net.SocketPermission noSuchMachine resolve)&#93;Adding this permission to the policy file has no effect. which means a priv block is required around the LDAP call.permission java.net.SocketPermission 'noSuchMachine'  'resolve';   