RMI endpoint doesn't handle nested exception and raise CamelRuntimeException instead of RemoteException    When we have a route looking like:&lt;from uri='rmi:...'/&gt;&lt;to uri='myBean'/&gt;if an exception is raised on myBean  the RMI endpoint ignores the exception described in the RemoteInterface and always raises a RuntimeCamelException nesting the original exceptions.More over  RuntimeCamalException should not be raised by the RMI endpoint. It would make more sense to raise a RemoteException  as we are on a RMI endpoint.   