<title>Issue 17540 -   chromium -    Occasional memory leak in base::MessagePumpLibevent::FileDescriptorWatcher in IPC::Channel::Connect() - Project Hosting on Google Code</title> <pre> This started failing with your checkin this morning  please investigate.  Feel free to close this if invalid or assign it to someone who can fix it.  Thanks  -Amit     Details:  08:26:29 memcheck_analyze.py [ERROR] FAIL! There were 1 errors:   08:26:29 memcheck_analyze.py [ERROR] Leak_DefinitelyLost  10 479 (72 direct  10 407 indirect) bytes in 1 blocks are definitely lost   in loss record 5 337 of 5 353    operator new(unsigned int) (ome/chrome-bot/valgrind-  20090715/coregrind/m_replacemalloc/vg_replace_malloc.c:213)    base::MessagePumpLibevent::WatchFileDescriptor(int  bool    base::MessagePumpLibevent::Mode    base::MessagePumpLibevent::FileDescriptorWatcher*    base::MessagePumpLibevent::Watcher*) (base/message_pump_libevent.cc:173)    MessageLoopForIO::WatchFileDescriptor(int  bool  MessageLoopForIO::Mode    base::MessagePumpLibevent::FileDescriptorWatcher*    base::MessagePumpLibevent::Watcher*) (base/message_loop.cc:629)    IPC::Channel::ChannelImpl::Connect() (ipc/ipc_channel_posix.cc:378)    IPC::Channel::Connect() (ipc/ipc_channel_posix.cc:818)    IPC::ChannelProxy::Context::OnChannelOpened()   (ipc/ipc_channel_proxy.cc:100)    IPC::SyncChannel::SyncContext::OnChannelOpened()   (ipc/ipc_sync_channel.cc:304)    RunnableMethod&lt;IPC::ChannelProxy::Context  void   (IPC::ChannelProxy::Context::*)()  Tuple0&gt;::Run() (base/tuple.h:412)    MessageLoop::RunTask(Task*) (base/message_loop.cc:313)    MessageLoop::DeferOrRunPendingTask(MessageLoop::PendingTask const&amp;)   (base/message_loop.cc:321)    MessageLoop::DoWork() (base/message_loop.cc:427)    base::MessagePumpLibevent::Run(base::MessagePump::Delegate*)   (base/message_pump_libevent.cc:224)    MessageLoop::RunInternal() (base/message_loop.cc:198)    MessageLoop::RunHandler() (base/message_loop.cc:181)    MessageLoop::Run() (base/message_loop.cc:155)    base::Thread::ThreadMain() (base/thread.cc:156)    ThreadFunc(void*) (base/platform_thread_posix.cc:26)    start_thread (/lib/tls/i686/cmov/libpthread-2.7.so)  Suppression:    fun:_Znwj      fun:_ZN4base19MessagePumpLibevent19WatchFileDescriptorEibNS0_4ModeEPNS0_21F  ileDescriptorWatcherEPNS0_7WatcherE      fun:_ZN16MessageLoopForIO19WatchFileDescriptorEibNS_4ModeEPN4base19MessageP  umpLibevent21FileDescriptorWatcherEPNS2_7WatcherE    fun:_ZN3IPC7Channel11ChannelImpl7ConnectEv    fun:_ZN3IPC7Channel7ConnectEv    fun:_ZN3IPC12ChannelProxy7Context15OnChannelOpenedEv    fun:_ZN3IPC11SyncChannel11SyncContext15OnChannelOpenedEv      fun:_ZN14RunnableMethodIN3IPC12ChannelProxy7ContextEMS2_FvvE6Tuple0E3RunEv    fun:_ZN11MessageLoop7RunTaskEP4Task    fun:_ZN11MessageLoop21DeferOrRunPendingTaskERKNS_11PendingTaskE    fun:_ZN11MessageLoop6DoWorkEv    fun:_ZN4base19MessagePumpLibevent3RunEPNS_11MessagePump8DelegateE    fun:_ZN11MessageLoop11RunInternalEv    fun:_ZN11MessageLoop10RunHandlerEv    fun:_ZN11MessageLoop3RunEv    fun:_ZN4base6Thread10ThreadMainEv    fun:_Z10ThreadFuncPv    fun:start_thread    08:26:29 valgrind_test.py [ERROR] Analyze failed.   </pre>