<title>Issue 20953 -   chromium -    Worker exceptions in onmessage handlers are not forwarded to the Worker object - Project Hosting on Google Code</title> <pre> This is the failure that keeps the worker-close.html layout test from   passing (testErrorAfterClose())  so we should uncomment this test from   worker_uitest.cc once it is fixed.    The repro is fairly simple:    Page code:    &lt;html&gt;    &lt;head&gt;    &lt;script&gt;      var worker = new Worker('w.js');      worker.postMessage(&quot;foo&quot;);      worker.onerror = function(a) {        alert(&quot;onerror: &quot; + a.message + &quot; &quot; + a.filename + &quot; &quot; + a.lineno);        return false;      }      worker.onmessage = function(event) {        alert(&quot;onmessage: &quot; + event.data);      }    &lt;/script&gt;  &lt;/head&gt;    &lt;body&gt;    &lt;p&gt;Worker Test&lt;/p&gt;  &lt;/body&gt;    &lt;/html&gt;      Worker code:    onmessage = function() {      var y = new XMLHttpRequest();      y.open(&quot;GET&quot; &quot;http://google.com&quot; false);      y.send(null);  }    This emits the exception to the console/stderr on the mac  but does not   forward it to page context.    We should probably also explicitly test this case in worker-script-  error.html (currently only tests errors that occur during the initial script   load/execution  rather than errors that happen at runtime).   </pre>