<title>Issue 20955 -   chromium -    Some pages on chromeextensionsdocs are failing - Project Hosting on Google Code</title> <pre> Example: <a href="http://chromeextensionsdocs.appspot.com/bookmarks.html">http://chromeextensionsdocs.appspot.com/bookmarks.html</a>    Traceback (most recent call last):    File   &quot;/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py&quot;  line   507  in __call__      handler.get(*groups)    File   &quot;/base/data/home/apps/chromeextensionsdocs/1.336016985258696659/chromeexten  sionsdocs.py&quot;  line 25  in get      page = self.get_page(url)    File   &quot;/base/data/home/apps/chromeextensionsdocs/1.336016985258696659/chromeexten  sionsdocs.py&quot;  line 32  in get_page      result = urlfetch.fetch(url + self.request.query_string)    File &quot;/base/python_lib/versions/1/google/appengine/api/urlfetch.py&quot;  line   241  in fetch      return rpc.get_result()    File   &quot;/base/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py&quot;    line 458  in get_result      return self.__get_result_hook(self)    File &quot;/base/python_lib/versions/1/google/appengine/api/urlfetch.py&quot;  line   338  in _get_fetch_result      raise ResponseTooLargeError(result)  ResponseTooLargeError    This is happening because those doc files are over 1Mb in size  which is   the limit for app engine.    Raf has found that this issue is caused by a bug in the doc file generation   logic and he is working on a fix. </pre>